name: analog_clock
description: Flutter Analog Clock plugin.
version: 0.0.4
author: Furkan Tektas <tektasfurkan@gmail.com>
homepage: https://github.com/furkantektas/analog_clock

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
