name: analog_clock
description: Flutter Analog Clock plugin.
version: 0.0.5
author: Furkan Tektas <tektasfurkan@gmail.com>
homepage: https://github.com/furkantektas/analog_clock

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: flutter.furkantektas.com.analog_clock
    pluginClass: AnalogClockPlugin
